// Generated by gencpp from file demo_msgs/Team3.msg
// DO NOT EDIT!


#ifndef DEMO_MSGS_MESSAGE_TEAM3_H
#define DEMO_MSGS_MESSAGE_TEAM3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <demo_msgs/Student.h>
#include <std_msgs/String.h>
#include <geometry_msgs/Twist.h>

namespace demo_msgs
{
template <class ContainerAllocator>
struct Team3_
{
  typedef Team3_<ContainerAllocator> Type;

  Team3_()
    : name()
    , leader()
    , intro()
    , location()  {
    }
  Team3_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , leader(_alloc)
    , intro(_alloc)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::demo_msgs::Student_<ContainerAllocator>  _leader_type;
  _leader_type leader;

   typedef  ::std_msgs::String_<ContainerAllocator>  _intro_type;
  _intro_type intro;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::demo_msgs::Team3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_msgs::Team3_<ContainerAllocator> const> ConstPtr;

}; // struct Team3_

typedef ::demo_msgs::Team3_<std::allocator<void> > Team3;

typedef boost::shared_ptr< ::demo_msgs::Team3 > Team3Ptr;
typedef boost::shared_ptr< ::demo_msgs::Team3 const> Team3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_msgs::Team3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_msgs::Team3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_msgs::Team3_<ContainerAllocator1> & lhs, const ::demo_msgs::Team3_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.leader == rhs.leader &&
    lhs.intro == rhs.intro &&
    lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_msgs::Team3_<ContainerAllocator1> & lhs, const ::demo_msgs::Team3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::demo_msgs::Team3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_msgs::Team3_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_msgs::Team3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_msgs::Team3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_msgs::Team3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_msgs::Team3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_msgs::Team3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f57c072b89f0cdd1735089d396821dae";
  }

  static const char* value(const ::demo_msgs::Team3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf57c072b89f0cdd1ULL;
  static const uint64_t static_value2 = 0x735089d396821daeULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_msgs::Team3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_msgs/Team3";
  }

  static const char* value(const ::demo_msgs::Team3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_msgs::Team3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"Student leader \n"
"std_msgs/String intro\n"
"geometry_msgs/Twist location \n"
"\n"
"================================================================================\n"
"MSG: demo_msgs/Student\n"
"string name\n"
"int32 age\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::demo_msgs::Team3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_msgs::Team3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.leader);
      stream.next(m.intro);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Team3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_msgs::Team3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_msgs::Team3_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "leader: ";
    s << std::endl;
    Printer< ::demo_msgs::Student_<ContainerAllocator> >::stream(s, indent + "  ", v.leader);
    s << indent << "intro: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.intro);
    s << indent << "location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_MSGS_MESSAGE_TEAM3_H
